### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' in leveler (Ubuntu,Bionic)

### ISSUE THREAD

**Issue by ghost** [fixator10/Fixator10-Cogs#11]
[2019-07-03 21:28:19] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/edgar06ka/bot/lib/python3.7/site-packages/redbot/core/core_commands.py", line 104, in _load
    await bot.load_extension(spec)
  File "/home/edgar06ka/bot/lib/python3.7/site-packages/redbot/core/bot.py", line 252, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 405, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 905, in load_module
  File "<frozen importlib._bootstrap_external>", line 730, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 726, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/edgar06ka/mybot/cogs/CogManager/cogs/leveler/__init__.py", line 1, in <module>
    from .leveler import Leveler
  File "/home/edgar06ka/mybot/cogs/CogManager/cogs/leveler/leveler.py", line 4, in <module>
    from PIL import Image, ImageDraw, ImageFont, ImageColor, ImageOps, ImageFilter
  File "/home/edgar06ka/mybot/cogs/Downloader/lib/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/edgar06ka/mybot/cogs/Downloader/lib/PIL/__init__.py)

**Comment by fixator10** [comment]
Start your bot with `--dev` argument and execute this command:
```
[p]eval import PIL
return PIL.__version__
```
*`[p]` is your prefix*

Returned value must be 6.0.0 or 6.1.0

**Comment by ghost** [comment]
Returned value is 5.1.0

**Comment by fixator10** [comment]
Do the `[p]pipinstall pillow` and restart your bot. Leveler is supports only pillow 6.0 and higher.
