### ISSUE TITLE
[Leveler] Updated red, now leveler doesn't load

### ISSUE THREAD

**Issue by viggou** [fixator10/Fixator10-Cogs#151]
**Describe the bug**

Can't load red, check logs below
**To Reproduce**

`!load leveler`
**Expected behavior**

**Bot's logs**

```
Feb 25 11:38:21 localhost redbot[1376]: [2022-02-25 11:38:21] [ERROR] red: Package loading failed
Feb 25 11:38:21 localhost redbot[1376]: Traceback (most recent call last):
Feb 25 11:38:21 localhost redbot[1376]:   File "/mnt/git/discordbot/cogs/CogManager/cogs/leveler/leveler.py", line 30, in <module>
Feb 25 11:38:21 localhost redbot[1376]:     from motor.motor_asyncio import AsyncIOMotorClient
Feb 25 11:38:21 localhost redbot[1376]:   File "/mnt/git/discordbot/cogs/Downloader/lib/motor/motor_asyncio.py", line 29, in <module>
Feb 25 11:38:21 localhost redbot[1376]:     AsyncIOMotorClient = create_asyncio_class(core.AgnosticClient)
Feb 25 11:38:21 localhost redbot[1376]:   File "/mnt/git/discordbot/cogs/Downloader/lib/motor/motor_asyncio.py", line 25, in create_asyncio_class
Feb 25 11:38:21 localhost redbot[1376]:     return create_class_with_framework(cls, asyncio_framework,
Feb 25 11:38:21 localhost redbot[1376]:   File "/mnt/git/discordbot/cogs/Downloader/lib/motor/metaprogramming.py", line 288, in create_class_with_framework
Feb 25 11:38:21 localhost redbot[1376]:     new_class_attr = attr.create_attribute(new_class, name)
Feb 25 11:38:21 localhost redbot[1376]:   File "/mnt/git/discordbot/cogs/Downloader/lib/motor/metaprogramming.py", line 204, in create_attribute
Feb 25 11:38:21 localhost redbot[1376]:     doc = getattr(cls.__delegate_class__, attr_name).__doc__
Feb 25 11:38:21 localhost redbot[1376]: AttributeError: type object 'MongoClient' has no attribute 'topology_description'
Feb 25 11:38:21 localhost redbot[1376]: During handling of the above exception, another exception occurred:
Feb 25 11:38:21 localhost redbot[1376]: Traceback (most recent call last):
Feb 25 11:38:21 localhost redbot[1376]:   File "/home/pix/vanilla/lib/python3.8/site-packages/redbot/core/core_commands.py", line 172, in _load
```

**Red version**

3.4.16
**Additional context**

**Comment by fixator10** [comment]
Try with last update, still same?

**Comment by xSignificant** [comment]
Still the same for me
